### ISSUE TITLE
youtube视频无法加载

### ISSUE THREAD

**Issue by LynnLululu** [udacity/wmpnd-cn#8]
## 教室地址
https://classroom.udacity.com/nanodegrees/nd666-cn-1/parts/0df2bc48-b519-43b3-94af-9e2fad59c3d2/modules/b30b76c5-6a21-4e31-8d1e-62a21ec8a8f4/lessons/5b9ac545-0d41-4eba-b685-eb681ac0391b/concepts/cfe9564e-f769-4ca4-81a2-bb9238151f49

## 截图
![image](https://user-images.githubusercontent.com/14273091/38852347-139916f6-424c-11e8-9172-158a1784aac9.png)

## 具体描述
视频链接：https://youtu.be/HD5yw7pdd4w
这个youtube视频无法加载，但是墙内的s3链接是正常的。

**Comment by evestorm** [comment]
已解决！感谢 @LynnLululu ~
